version: "3"

services:
  # ---- ACCEPTORS ---- #
  acceptor1:
    build: .
    environment:
      - LIFETIME=10.0
      - PLR=0.1
      - ROLE=acceptor
      - ID=1
  acceptor2:
    build: .
    environment:
      - PLR=0.1
      - ROLE=acceptor
      - ID=2
  acceptor3:
    build: .
    environment:
      - PLR=0.1
      - ROLE=acceptor
      - ID=4

  # ---- PROPOSERS ---- #
  proposer1:
    build: .
    environment:
      - PLR=0.1
      - ROLE=proposer
      - ID=1
    depends_on:
      - acceptor1
      - acceptor2
      - acceptor3

  # ---- LEARNERS ---- #
  learner1:
    build: .
    environment:
      - PLR=0.1
      - ROLE=learner
      - ID=1
    depends_on:
      - acceptor1
      - acceptor2
      - acceptor3
  learner2:
    build: .
    environment:
      - PLR=0.1
      - ROLE=learner
      - ID=2
    depends_on:
      - acceptor1
      - acceptor2
      - acceptor3

  # ---- CLIENTS ---- #
  client1:
    build: .
    stdin_open: true
    tty: true
    environment:
      - PLR=0.1
      - ROLE=client
      - ID=2
    depends_on:
      - proposer1
