#!/bin/bash

# ---- VARIABLES ---- #
NETWORK_SIZE=2
SELF_ROLE="learner"
SELF_ID=$1
CONFIG_PATH=$2
PLR=$3

# ---- PROGRAM EXECUTION ---- #
python3 ./main.py $SELF_ROLE $SELF_ID $CONFIG_PATH $NETWORK_SIZE $PLR
